
runtime: python39

entrypoint: gunicorn -b :$PORT myapp.wsgi

env_variables:
  SECRET_KEY: ''
  DATABASE_URL: /db.sqlite3

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
